# Generated by Django 3.2.7 on 2021-09-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified at')),
                ('name', models.CharField(max_length=40, verbose_name='circle name')),
                ('sku', models.CharField(max_length=12, verbose_name='circle name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brand', models.CharField(max_length=40, verbose_name='circle name')),
            ],
            options={
                'ordering': ['-name'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
