# Generated by Django 3.2.7 on 2021-09-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=True, help_text=('Help easily distinguish product and perform queries.',), verbose_name='product'),
        ),
    ]
