# Generated by Django 3.2.7 on 2021-09-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=12, unique=True, verbose_name='circle name'),
        ),
    ]
