# Generated by Django 3.2.7 on 2021-09-28 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20210928_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_user_relationship',
            field=models.ManyToManyField(through='products.ProductUserRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
